config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users
  # ログイン・ログアウト
  resource :session, only: [ :new, :create, :destroy ]

  # FacebookでログインとScreenName作成
  resource :user_identity, only: [ :new, :create ] do
    post :confirm, on: :collection
  end

  get 'auth/facebook/callback', to: "sessions#callback"
  get "auth/failure", to: "sessions#failure"

  resources :results
  resources :games do
    resources :individual_results
    resources :pitcher_results
  end
  resources :schedules
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    if params[:change].present?
      day_array = params[:change].unpack("a4a2")
      @year = day_array[0].to_i
      @month = day_array[1].to_i
    else
      @month = Time.now.month
      @year = Time.now.year
    end
    @now_month = Date.new(@year,@month,1)
    @schedules = Schedule.new(@year,@month).make_array
  end
end

app/views/schedules/index.html.erb
<div class="panel panel-custom full">
  <div class="panel-heading">
    <p>
      <span style="float: left;"><%= link_to "<<", schedules_path(change: "#{@now_month.last_month.strftime('%Y%m')}") %></span>
      <%= @year %>年<%= @month %>月
      <span style="float: right;"><%= link_to ">>", schedules_path(change: "#{@now_month.next_month.strftime('%Y%m')}") %></span>
    </p>
  </div>
  <div class="panel-body" style="text-align: center;">
    <table class="schedule" border="1">
      <tr>
        <th class="sun">日</th>
        <th>月</th>
        <th>火</th>
        <th>水</th>
        <th>木</th>
        <th>金</th>
        <th class="sat">土</th>
      </tr>
      <% @schedules.each do |schedule| %>
        <tr>
          <% schedule.each_with_index do |day, i| %>
            <% if i == 0 %>
              <td class="sun"><%= day %></td>
            <% elsif i == 6 %>
              <td class="sat"><%= day %></td>
            <% else %>
              <td><%= day %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
</div>