config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  resources :users
  # ログイン・ログアウト
  resource :session, only: [ :new, :create, :destroy ]

  # FacebookでログインとScreenName作成
  resource :user_identity, only: [ :new, :create ] do
    post :confirm, on: :collection
  end

  get 'auth/facebook/callback', to: "sessions#callback"
  get "auth/failure", to: "sessions#failure"

  resources :results
  resources :games do
    resources :individual_results
    resources :pitcher_results
  end
  resources :schedules
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    @season = Season.find_by(use: true)
    regulation_number = @season.games.count * 1.4
    regulation_pitcher_number = @season.games.count * 1
    @results = @season.individual_total_results.
      where("#{regulation_number} < plate_appearances")
    @no_results = @season.individual_total_results
    @pitcher_results = @season.pitcher_total_results.
      where("#{regulation_pitcher_number} < pitching_number")
    # 野手成績
    if params[:change].present?
      if params[:change] == "game_count"
        @results = @results.sort{|a, b| b.set_games.count <=> a.set_games.count }
      elsif params[:change] == "hits"
        @results = @results.order("(single_hits + double_hits + triple_hits + home_run) DESC")
      elsif params[:change] == "total_bases"
        @results = @results.order("(single_hits + double_hits * 2 + triple_hits * 3 + home_run * 4) DESC")
      else
        @results = @results.order("#{params[:change]} DESC")
      end
    else
      @results = @results.order("batting_average DESC")
    end

    # 投手成績
    if params[:p_change].present?
      if params[:p_change] == "game_count"
        @pitcher_results = @pitcher_results.sort{|a, b| b.set_games.count <=> a.set_games.count }
      else
        @pitcher_results = @pitcher_results.order("#{params[:p_change]} DESC")
      end
    end
  end
end

app/views/results/_games.html.erb
<div class="panel panel-custom full">
  <div class="panel-heading">
    <p>試合結果</p>
  </div>
  <div class="panel-body">
    <table class="result" border="1">
      <tr>
        <th>試合日</th>	
        <th>試合名</th>	
        <th>勝敗</th>
        <th>結果</th>
        <th>コメント</th>
      </tr>
      <% @season.games.order("played_at DESC").each_with_index do |result, idx| %>
        <tr>
          <td style="white-space: nowrap;"><%= result.played_at.strftime("%Y/%m/%d") %></td>
          <td style="white-space: nowrap;"><%= result.name %></td>
          <td style="white-space: nowrap;"><%= result.display_winning %></td>
          <td style="white-space: nowrap;"><%= result.total_result %></td>
          <td><%= result.description %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/results/_pitcher_results.html.erb
<div class="panel panel-custom full">
  <div class="panel-heading">
    <p>投手成績</p>
  </div>
  <div class="panel-body">
    <table class="result" border="1">
      <tr>
        <th>順位</th>
        <th>選手名</th>
        <th><%= link_to "防御率*", results_path(p_change: "earned_run_average") %></th>
        <th><%= link_to "試合数", results_path(p_change: "game_count") %></th>
        <th><%= link_to "勝", results_path(p_change: "winning") %></th>
        <th><%= link_to "敗*", results_path(p_change: "defeat") %></th>
        <th><%= link_to "ホールド", results_path(p_change: "hold_number") %></th>
        <th><%= link_to "セーブ", results_path(p_change: "save_number") %></th>
        <th><%= link_to "勝率*", results_path(p_change: "winning_rate") %></th>
        <th><%= link_to "投球回数", results_path(p_change: "pitching_number") %></th>
        <th><%= link_to "被安打*", results_path(p_change: "hit") %></th>
        <th><%= link_to "奪三振", results_path(p_change: "strikeouts") %></th>
        <th><%= link_to "奪三振率*", results_path(p_change: "struck_out_rate") %></th>
        <th><%= link_to "失点", results_path(p_change: "run") %></th>
        <th><%= link_to "自責点", results_path(p_change: "remorse_point") %></th>
      </tr>
      <% @pitcher_results.each_with_index do |result, idx| %>
        <tr>
          <td><%= idx + 1 %></td>
          <td><%= result.user.display_name %></td>
          <td><%= sprintf( "%.2f", result.earned_run_average.to_f) %></td>
          <td><%= result.set_games.count %></td>
          <td><%= result.winning %></td>
          <td><%= result.defeat %></td>
          <td><%= result.hold_number %></td>
          <td><%= result.save_number %></td>
          <td><%= sprintf("%.3f", result.winning_rate.to_f) %></td>
          <td><%= result.pitching_number %></td>
          <td><%= result.hit %></td>
          <td><%= result.strikeouts %></td>
          <td><%= result.struck_out_rate %></td>
          <td><%= result.run %></td>
          <td><%= result.remorse_point %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/results/_results.html.erb
<div class="panel panel-custom full">
  <div class="panel-heading">
    <p>野手成績</p>
  </div>
  <div class="panel-body">
    <table class="result" border="1">
      <tr>
        <th>順位</th>
        <th>選手名</th>
        <th><%= link_to "打率*", results_path(change: "batting_average") %></th>
        <th><%= link_to "試合数", results_path(change: "game_count") %></th>
        <th><%= link_to "打席数", results_path(change: "plate_appearances") %></th>
        <th><%= link_to "打数", results_path(change: "at_bats") %></th>
        <th><%= link_to "安打", results_path(change: "hits") %></th>
        <th><%= link_to "二塁打", results_path(change: "double_hits") %></th>
        <th><%= link_to "三塁打", results_path(change: "triple_hits") %></th>
        <th><%= link_to "本塁打", results_path(change: "home_run") %></th>
        <th><%= link_to "塁打数", results_path(change: "total_bases") %></th>
        <th><%= link_to "打点", results_path(change: "runs_batted_in") %></th>
        <th><%= link_to "得点", results_path(change: "runs_scored") %></th>
        <th><%= link_to "三振", results_path(change: "strikeouts") %></th>
        <th><%= link_to "四球", results_path(change: "base_on_balls") %></th>
        <th><%= link_to "死球", results_path(change: "hit_by_pitches") %></th>
        <th><%= link_to "犠打", results_path(change: "sacrifice_bunts") %></th>
        <th><%= link_to "犠飛", results_path(change: "sacrifice_flies") %></th>
        <th><%= link_to "盗塁", results_path(change: "stolen_bases") %></th>
        <th><%= link_to "出塁率*", results_path(change: "base_percentage") %></th>
        <th><%= link_to "長打率*", results_path(change: "slugging_percentage") %></th>
      </tr>
      <% @results.each_with_index do |result, idx| %>
        <tr>
          <td><%= idx + 1 %></td>
          <td><%= result.user.display_name %></td>
          <td><%= sprintf( "%.3f", result.batting_average.to_f) %></td>
          <td><%= result.set_games.count %></td>
          <td><%= result.plate_appearances %></td>
          <td><%= result.at_bats %></td>
          <td><%= result.total_hits %></td>
          <td><%= result.double_hits %></td>
          <td><%= result.triple_hits %></td>
          <td><%= result.home_run %></td>
          <td><%= result.total_bases %></td>
          <td><%= result.runs_batted_in %></td>
          <td><%= result.runs_scored %></td>
          <td><%= result.strikeouts %></td>
          <td><%= result.base_on_balls %></td>
          <td><%= result.hit_by_pitches %></td>
          <td><%= result.sacrifice_bunts %></td>
          <td><%= result.sacrifice_flies %></td>
          <td><%= result.stolen_bases %></td>
          <td><%= sprintf( "%.3f", result.base_percentage.to_f) %></td>
          <td><%= sprintf( "%.3f", result.slugging_percentage.to_f) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/results/index.html.erb
<%= link_to "新規作成", :new_game, class: "btn-btn-lg btn-primary btn-block" %>
<br/>

<div class="panel panel-custom full">
  <div class="panel-heading">
    <p>結果</p>
  </div>
  <div class="panel-body" style="text-align: center;">
    <strong>
      <%= @season.games.map(&:winning).count {|a| a == 0 } %>勝
      <%= @season.games.map(&:winning).count {|a| a == 1 } %>負
      <%= @season.games.map(&:winning).count {|a| a == 2 } %>引き分け
      <%
        b = @season.pitcher_total_results.map(&:remorse_point).inject(:+)
        c = @season.pitcher_total_results.map(&:pitching_number).inject(:+)
        d = (b * 9).quo(c).to_f.round(2)
      %>
      防御率：<%= d %>
      <%
        a = @season.games.map(&:at_bats).inject(:+)
        t = @season.games.map(&:single).inject(:+) +
          @season.games.map(&:double).inject(:+) +
          @season.games.map(&:triple).inject(:+) +
          @season.games.map(&:home_run).inject(:+)
      %>
      打率：<%= sprintf( "%.3f", t.quo(a).to_f.round(3)) %>
    </strong>
  </div>
</div>

<!-- 試合 -->
<%= render "results/games" %>
<!-- 投手 -->
<%= render "results/pitcher_results" %>
<!-- 野手 -->
<%= render "results/results" %>